export const AllSentences = [

  {
    id: 1,
    categoria: "Bom dia",
    frases: [
      "Bom dia, programadores! Que seus códigos sejam tão eficientes quanto seu primeiro café da manhã",
      "Bom dia! Que sua jornada de codificação comece com um 'commit' de sucesso",
      "Para os programadores que acordam cedo: bom dia, café quente e código na tela!",
      "Bom dia, mundo! E aos programadores, que cada 'bug' seja um novo desafio a ser vencido",
      "Bom dia para os mestres da lógica e da criatividade: os programadores!",
      "Que o dia de hoje seja como um código bem estruturado: organizado e sem erros",
      "Bom dia, devs! Que a sintaxe esteja a seu favor e os semicolons não se percam pelo caminho",
      "Para os que transformam café em código: bom dia e que a inspiração esteja com vocês",
      "Bom dia para os que acordam com a mente cheia de algoritmos e o coração cheio de paixão pela programação",
      "Bom dia, colegas de código! Que a depuração seja breve e os resultados sejam grandiosos",
      "Para os que enfrentam os desafios do código: bom dia, persistência e muita cafeína!",
      "Bom dia para os programadores, que transformam linhas de código em soluções incríveis!",
      "Que o dia comece com um 'Hello, World!' e termine com um 'Goodbye, Bugs!'",
      "Bom dia, devs! Que o terminal esteja a seu favor e as consultas SQL sejam eficazes",
      "Bom dia para os que vivem entre chaves e parênteses: que o dia seja bem formado e sem erros de sintaxe",
      "Para os que sonham com loops e arrays: bom dia, que a jornada seja tão fascinante quanto um novo projeto",
      "Bom dia, programadores! Que cada linha de código seja uma conquista e cada desafio, uma oportunidade",
      "Que o dia de hoje seja cheio de commits bem-sucedidos e merges sem conflitos",
      "Bom dia para os que criam mundos virtuais a partir de linhas de código: que a criatividade nunca se esgote",
      "Bom dia, colegas de desenvolvimento! Que o dia seja produtivo e as ideias sejam inovadoras",
      "Para os que encontram beleza na estruturação do código: bom dia e que a elegância esteja presente em cada linha",
      "Bom dia, programadores! Que a resolução de bugs seja rápida e as implementações, perfeitas",
      "Bom dia para os que veem em cada desafio uma oportunidade de crescimento e aprendizado",
      "Que o dia comece com um 'import happiness' e termine com um 'export sucesso'!",
      "Bom dia, devs! Que a jornada de hoje seja repleta de conquistas e novas descobertas",
      "Bom dia para os que transformam café em código e bugs em soluções!",
      "Que cada linha de código escrito hoje seja um passo em direção ao sucesso",
      "Bom dia, programadores! Que a compilação seja rápida e os testes, confiáveis",
      "Bom dia para os que têm o coração em hexadecimal e a mente em binário",
      "Que o debugger esteja sempre ao seu lado, e os erros, longe do seu código",
      "Bom dia, devs! Que hoje seja um dia de muita criatividade e novas ideias",
      "Bom dia para os que têm paciência para encontrar o ponto e vírgula perdido",
      "Que o café seja forte, o código esteja limpo e as ideias sejam brilhantes",
      "Bom dia, programadores! Que os algoritmos fluam como música aos seus ouvidos",
      "Bom dia para os que entendem que um código bem escrito vale mais que mil palavras",
      "Que o compilador seja seu aliado e os bugs, meras lembranças do passado",
      "Bom dia, devs! Que hoje seja um dia de código limpo e design elegante",
      "Bom dia para os que sonham em código e acordam com a solução na mente",
      "Que o café te dê energia e o código te dê alegria nesta jornada de programação",
      "Bom dia, programadores! Que as linhas de código sejam claras e semânticas como poesia",
      "Que cada função escrita hoje seja uma vitória no mundo da programação",
      "Bom dia para os que sabem que o segredo está nos detalhes do código",
      "Que hoje seja um dia de boas práticas, testes rigorosos e resultados surpreendentes",
      "Bom dia, devs! Que cada bug encontrado seja um degrau a mais na escada do conhecimento",
      "Bom dia para os que encontram beleza nos algoritmos e perfeição nas estruturas de dados",
      "Que o café seja quente, o código seja limpo e o dia seja produtivo",
      "Bom dia, programadores! Que hoje seja um dia de desafios vencidos e projetos concluídos",
    ]
  },

  {
    id: 2,
    categoria: "Motivação",
    frases: [
      "Aprender a programar é como aprender um novo idioma - quanto mais você pratica, melhor você fica",
      "Programador é igual a feijão: só passa aperto se estiver sem 'Java'",
      "Quem nunca fez um 'print' para ver se o código está funcionando, não sabe o que é emoção",
      "O verdadeiro desenvolvedor só se contenta com a versão beta da vida",
      "Se a vida te der limões, troque por café e escreva mais código",
      "Quem nunca quebrou a cabeça com um loop infinito, não sabe o que é perder a paciência",
      "Os bugs são como pokémons: você os encontra quando menos espera",
      "Na dúvida, 'commita' e depois 'pusha' - é melhor prevenir do que perder o código",
      "O código é a poesia da máquina, escrita em uma linguagem que só os computadores entendem",
      "Programador que é programador sabe: os melhores algoritmos nascem na madrugada",
      "O verdadeiro desafio não é resolver um bug, é encontrar o momento perfeito para tomar café",
      "Quem nunca escreveu um código que funcionou perfeitamente na primeira tentativa, está mentindo",
      "A vida de um programador é um ciclo infinito: escrever código, testar, debugar, repetir",
      "Boas práticas de programação são como vitaminas para o código: essenciais para a saúde",
      "O céu é o limite para um programador, mas às vezes o código vai até a lua e volta",
      "Para o computador, o código é como uma história de suspense - cheio de plot twists",
      "Se a vida fosse um programa, o amor seria o loop infinito",
      "Quem nunca pediu ajuda no Stack Overflow, não sabe o que é se sentir parte de uma comunidade",
      "O código é como uma receita de bolo: siga os passos corretamente e terá um resultado delicioso",
      "Para o programador, a perfeição é uma ilusão - a busca pelo código ideal é interminável",
      "O código-fonte é a arte do desenvolvedor, sua criação mais valiosa",
      "Programar é como construir um castelo de cartas: um pequeno erro pode derrubar tudo",
      "Se o código fosse um país, a documentação seria o mapa - essencial para não se perder",
      "Programador que é programador sonha com código - até mesmo nos momentos de sono",
      "Na vida de um programador, a única constante é a mudança do código"

    ]
  },
  {
    id: 3,
    categoria: "Trabalho em equipe",
    frases: [
      "Trabalhar em equipe é como um código bem escrito: cada parte contribui para o todo",
      "Para os programadores que sabem que juntos, somos mais fortes: equipe unida é equipe vencedora!",
      "O segredo do sucesso está na colaboração: equipe de desenvolvimento, pronta para os desafios!",
      "Trabalho em equipe é dividir as tarefas e multiplicar as conquistas",
      "Juntos somos mais do que a soma das nossas habilidades individuais: somos uma equipe imbatível",
      "Que a sinergia da nossa equipe nos leve além dos limites do código",
      "Equipe de desenvolvimento, unida e focada em alcançar grandes resultados!",
      "Trabalhar em equipe é como um repositório Git: cada contribuição faz o projeto evoluir",
      "Que a união da nossa equipe seja tão sólida quanto um bloco de código bem estruturado",
      "Para os que acreditam que as melhores soluções são criadas em equipe: equipe unida, projetos incríveis!",
      "O sucesso de um projeto está na harmonia e colaboração da equipe de desenvolvimento",
      "Equipe de programadores, pronta para superar desafios e alcançar objetivos!",
      "Trabalhar em equipe é como resolver um bug difícil: juntos, encontramos a solução",
      "Que a nossa equipe seja um exemplo de cooperação, eficiência e criatividade",
      "Para os programadores que sabem que grandes projetos só são possíveis com uma equipe unida",
      "Equipe de desenvolvimento, cada membro é peça chave para o sucesso!",
      "Trabalhar em equipe é como ter diferentes perspectivas que se unem para criar algo extraordinário",
      "Que cada membro da nossa equipe seja como uma linha de código: essencial para o funcionamento do todo",
      "Equipe de programadores, juntos podemos transformar desafios em oportunidades!",
      "Trabalhar em equipe é encontrar as soluções mais criativas e eficientes para os desafios",
      "Que a nossa equipe seja uma fonte de inspiração e motivação para conquistar novos desafios",
      "Para os programadores que sabem que juntos podemos transformar linhas de código em inovação",
      "Equipe de desenvolvimento, colaboração é a chave para o sucesso!",
      "Trabalhar em equipe é como escrever um código colaborativo: cada um contribui com sua expertise",
      "Que a nossa equipe seja uma força unida, pronta para superar qualquer desafio!"
    ]
  },
  {
    id: 4,
    categoria: "Humor",
    frases: [
      "Programador não é preguiçoso, só gosta de encontrar soluções eficientes",
      "Otimização de código é como tirar um coelho da cartola",
      "Quem nunca clicou 'Salvar' depois de escrever só uma linha de código, não sabe o que é adrenalina!",
      "Debugar é humano, resolver o problema no primeiro 'print' é divino",
      "O café é a gasolina do desenvolvedor",
      "Cada bug corrigido é um novo bug gerado",
      "Em um mundo de zeros e uns, seja um três!",
      "A melhor maneira de aprender é errar o código várias vezes",
      "Programador não bebe, só faz 'download' da cerveja",
      "Eu não cometo erros, só descubro novas maneiras de não fazer o código",
      "Se o código compilar na primeira vez, você provavelmente esqueceu algo",
      "Quem nunca deu 'Ctrl + C' no mundo real, quando algo deu errado?",
      "Por que o programador foi preso? Porque ele deletou todos os seus 'cookies'!",
      "Código bom é código comentado pelo colega de trabalho",
      "O programador mora nos detalhes, mas paga aluguel na vírgula",
      "Programar é fácil, como andar de bicicleta. Exceto que a bicicleta está em chamas e você está no inferno",
      "A melhor parte do código é o código que não está lá",
      "As melhores ideias surgem quando você está no chuveiro, ou tentando resolver um bug",
      "Por que o desenvolvedor odeia matemática? Porque ele tem traumas de cálculos infinitos!",
      "Se não está quebrado, adicione mais uma função!",
      "'Quem nunca programou não sabe o que é sofrer com um código que compila, mas não funciona!'",
      "Cerveja é igual a software: só é grátis se você tiver o código-fonte!",
      "A melhor maneira de lembrar algo é não comentar no código",
      "O problema do mundo é que toca uma música de erro, e todo mundo acha que é com ele!",
      "Se o código estiver funcionando e você não souber por que, não mexa!"
    ]
  }
]